/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#6ffbbe",
        "on-primary-fixed-variant": "#264191",
        "on-secondary-fixed-variant": "#3a4858",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-container": "#90a8ff",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#444651",
        "secondary-container": "#d5e4f8",
        "on-surface": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed": "#002113",
        "surface-bright": "#f8f9ff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b9c8db",
        "primary-fixed": "#dce1ff",
        "on-tertiary-container": "#27c38a",
        "surface-dim": "#cbdbf5",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#576676",
        "surface-container": "#e5eeff",
        "surface-container-highest": "#d3e4fe",
        "inverse-primary": "#b6c4ff",
        "surface-container-high": "#dce9ff",
        "on-error": "#ffffff",
        "tertiary": "#00311f",
        "secondary": "#516070",
        "surface-variant": "#d3e4fe",
        "secondary-fixed": "#d5e4f8",
        "primary": "#00236f",
        "primary-container": "#1e3a8a",
        "background": "#f8f9ff",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-surface": "#213145",
        "on-primary-fixed": "#00164e",
        "tertiary-container": "#004a31",
        "on-background": "#0b1c30",
        "on-secondary-fixed": "#0e1d2b",
        "outline-variant": "#c5c5d3",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eaf1ff",
        "surface": "#f8f9ff",
        "error-container": "#ffdad6",
        "outline": "#757682",
        "surface-tint": "#4059aa"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "cell-padding-x": "0.75rem",
        "container-max": "1280px",
        "edge-margin": "1.5rem",
        gutter: "1rem",
        "cell-padding-y": "0.5rem",
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "display-score": ["Inter"],
        "title-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "data-tabular": ["Inter"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-score": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "data-tabular": ["13px", { lineHeight: "18px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
